export const POST_TYPES = {
  SEARCH_POST: "SEARCH_POST",
  IS_EDIT_POST: "IS_EDIT_POST",
  ON_MODAL_POST: "ON_MODAL_POST",
  GET_POSTS: "GET_POSTS",
  GET_POST: "GET_POST",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
};
